language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer dump-autoload -o

script:
  composer test